name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |

            echo "🔐 Logging into ghcr.io on the VPS..."
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
  
            echo "🛑 Stopping existing container (if any)..."
            docker stop xenty || true && docker rm xenty || true
  
            echo "⬇️ Pulling latest image..."
            docker pull ghcr.io/${{ github.repository }}:latest
  
            echo "🚀 Starting new container..."
            docker run -d \
              --name xenty \
              -p 8501:8501 \
              -v /home/ubuntu/xenty/data:/app/data \
              -env-file /home/ubuntu/xenty/.env \
              ghcr.io/${{ github.repository }}:latest