name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: 22
          debug: true
          script: |
            echo "🔐 Logging into ghcr.io on the VPS..."
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
  
            echo "🛑 Stopping existing container (if any)..."
            docker stop xenty || true && docker rm xenty || true
  
            echo "⬇️ Pulling latest image..."
            docker pull ghcr.io/${{ github.repository }}:latest
  
            echo "🚀 Starting new container..."
            docker run -d \
              --name xenty \
              -p 80:8501 \
              -v .:/app \
              ghcr.io/${{ github.repository }}:latest